spring:
  profiles: default # 로컬환경에서만 사용하기

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    #    key-store: classpath:keystore.p12(로컬뿐 아닌 개발서버에서도 사용하려면)
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 8888
